apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.etcd.host }}
spec:
  ports:
  - name: db
    targetPort: {{ .Values.etcd.port }}
    port: {{ .Values.etcd.port }}
  selector:
    app: {{ .Values.etcd.host }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.etcd.host }}
  labels:
    app.kubernetes.io/component: {{ .Values.etcd.host }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.etcd.host }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.etcd.host }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.etcd.host }}
          image: {{ .Values.etcd.image }}
          ports:
          - containerPort: {{ .Values.etcd.port }}
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
            requests:
              memory: "100Mi"
          env:
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://{{ .Values.etcd.host }}:{{ .Values.etcd.port }}"