{{- if not .Values.isOkteto }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.grpcUi.host }}-gateway
  {{- if not .Values.isOkteto }}
  namespace: {{ .Values.grpcUi.namespace }}
  {{ end }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "ui.{{ .Values.domain }}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  {{- if not .Values.isOkteto }}
  namespace: {{ .Values.grpcUi.namespace }}
  {{ end }}
  name: {{ .Values.grpcUi.host }}
spec:
  hosts:
  - "ui.{{ .Values.domain }}"
  gateways:
  - {{ .Values.grpcUi.host }}-gateway
  http:
  - route:
    - destination:
        host: {{ .Values.grpcUi.host }}
        port:
          number: {{ .Values.grpcUi.port }}
---
{{ end }}
apiVersion: v1
kind: Service
metadata:
  {{- if not .Values.isOkteto }}
  namespace: {{ .Values.grpcUi.namespace }}
  {{ end }}
  name: {{ .Values.grpcUi.host }} 
  {{ if .Values.isOkteto }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
  {{ end }}
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 8080
  selector:
    app: {{ .Values.grpcUi.host }} 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if not .Values.isOkteto }}
  namespace: {{ .Values.grpcUi.namespace }}
  {{ end }}
  name: {{ .Values.grpcUi.host }}
  labels:
    app.kubernetes.io/component: {{ .Values.grpcUi.host }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.grpcUi.host }} 
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.grpcUi.host }} 
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      - name: {{ .Values.grpcUi.host }} 
        image: {{ .Values.grpcUi.image }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "300m"
            memory: "400Mi"
          requests:
            cpu: "200m"
            memory: "200Mi"
        env:
          - name: GRPCUI_SERVER
            value: {{ include "grpc.gateway" .}}